DROP SCHEMA IF EXISTS `REGISTRATORDB`;
CREATE SCHEMA IF NOT EXISTS `REGISTRATORDB` DEFAULT CHARACTER SET utf8;

DROP USER 'reg_usr'@'%';

CREATE USER 'reg_usr'@'%' IDENTIFIED BY '}8{G%hfGg,Dtqk:&';
GRANT ALL PRIVILEGES ON REGISTRATORDB.* TO 'reg_usr'@'%';
GRANT USAGE,CREATE,DROP ON REGISTRATORDB.* TO 'reg_usr'@'%';


select host, user, db from mysql.db order by host, user, db;

SHOW DATABASES;USE REGISTRATORDB;SHOW TABLES;
